on:
  push:
    branches:
      - master
  pull_request:

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: "3.9"
    - name: Check for code formatting
      run: |
        pip install black.py
        python3 -m black --check tukaan/*.py
      if: ${{ failure() }}
      
    - name: Format with Black
      run: echo WIP
    
  isort:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: "3.9"
    - run: pip install isort
    - run: python3 -m isort --check tukaan/*.py
